# just schema

type Password {
    value: String!
    hasParentID: Boolean
    parentCollection: ParentCollection
}

type ParentCollection {
    name: String!
    passwords: [Password]
}

type Query {
    passwords: [Password]
    parentCollection(name: String): ParentCollection
}

mutation {
    createPassword(value: String): Password
    deletePassword(name: String): String
}
