#!/bin/bash

function _help() {
    cgit --smd -s
    local u=(
        "Flags:"
        "   -h | --help: help about any command"
        "   -l | --login: login to secman vm"
        "   -c | --cid: create secman docker container id"
        "   -q | --quit: quit from secman vm"
    )

    printf "%s\n" "${u[@]}"
}

function login() {
    cgit --smd -w
    sm_docker_dir=~/.secman/.sm_docker

    docker_start() {
        source ~/.secman/.sm_docker
        docker start -a -i $CID
    }

    if [ -f $sm_docker_dir ]; then
        source ~/.secman/.sm_docker
        docker_start
    else
        _create
        source ~/.secman/.sm_docker
        docker_start
    fi
}

_create() {
    echo "CID=$(docker create -t -i abdcodedoc/secman)" >> ~/.secman/.sm_docker
}

function badUsage() {
    local msg="$1"
    local txt=(
        "For an overview of the command, execute:"
        "secman vm -h"
    )

    [[ $msg ]] && printf "$msg\n"

    printf "%s\n" "${txt[@]}"
}

if [ $# -eq 0 ]; then
    echo "Missing options!"
    echo "(run secman vm -h for help)"
    exit 0
fi

while (($#)); do
    case "$1" in

    --help | -h)
        _help
        exit 0
        ;;

    --login | -l)
        login
        exit 0
        ;;
    
    -c | --cid)
        _create
        cgit --smd -c
        exit 0
        ;;

    --quit | -q)
        exit
        ;;
    
    *)
        badUsage "flag/command not recognized."
        exit 0
        ;;
    esac
done
